// Stub functions for protofile "cdplayer_protos.h"
// Generated by genPPCStub 1.1 for StormC
// © 1996/97 HAAGE & PARTNER GmbH

// DO NOT EDIT

#ifndef PPC
#define PPC
#endif // PPC

#include <libraries/powerpc.h>

#include <ppcamiga.h>

BYTE CDEject(void *arg1)
{
	extern struct Library *CDPlayerBase;
	ULONG regs[16];
	regs[13] = (ULONG) arg1;
	__CallLibrary(CDPlayerBase,-30,regs);
	return (BYTE) regs[0];
}

BYTE CDPlay(UBYTE arg1,UBYTE arg2,void *arg3)
{
	extern struct Library *CDPlayerBase;
	ULONG regs[16];
	regs[8] = (ULONG) arg1;
	regs[9] = (ULONG) arg2;
	regs[13] = (ULONG) arg3;
	__CallLibrary(CDPlayerBase,-36,regs);
	return (BYTE) regs[0];
}

BYTE CDResume(BOOL arg1,void *arg2)
{
	extern struct Library *CDPlayerBase;
	ULONG regs[16];
	regs[8] = (ULONG) arg1;
	regs[13] = (ULONG) arg2;
	__CallLibrary(CDPlayerBase,-42,regs);
	return (BYTE) regs[0];
}

BYTE CDStop(void *arg1)
{
	extern struct Library *CDPlayerBase;
	ULONG regs[16];
	regs[13] = (ULONG) arg1;
	__CallLibrary(CDPlayerBase,-48,regs);
	return (BYTE) regs[0];
}

BYTE CDJump(ULONG arg1,void *arg2)
{
	extern struct Library *CDPlayerBase;
	ULONG regs[16];
	regs[8] = (ULONG) arg1;
	regs[13] = (ULONG) arg2;
	__CallLibrary(CDPlayerBase,-54,regs);
	return (BYTE) regs[0];
}

BOOL CDActive(void *arg1)
{
	extern struct Library *CDPlayerBase;
	ULONG regs[16];
	regs[13] = (ULONG) arg1;
	__CallLibrary(CDPlayerBase,-60,regs);
	return (BOOL) regs[0];
}

ULONG CDCurrentTitle(void *arg1)
{
	extern struct Library *CDPlayerBase;
	ULONG regs[16];
	regs[13] = (ULONG) arg1;
	__CallLibrary(CDPlayerBase,-66,regs);
	return (ULONG) regs[0];
}

BYTE CDTitleTime(void *arg1,void *arg2)
{
	extern struct Library *CDPlayerBase;
	ULONG regs[16];
	regs[8] = (ULONG) arg1;
	regs[13] = (ULONG) arg2;
	__CallLibrary(CDPlayerBase,-72,regs);
	return (BYTE) regs[0];
}

BYTE CDGetVolume(void *arg1,void *arg2)
{
	extern struct Library *CDPlayerBase;
	ULONG regs[16];
	regs[8] = (ULONG) arg1;
	regs[13] = (ULONG) arg2;
	__CallLibrary(CDPlayerBase,-78,regs);
	return (BYTE) regs[0];
}

BYTE CDSetVolume(void *arg1,void *arg2)
{
	extern struct Library *CDPlayerBase;
	ULONG regs[16];
	regs[8] = (ULONG) arg1;
	regs[13] = (ULONG) arg2;
	__CallLibrary(CDPlayerBase,-84,regs);
	return (BYTE) regs[0];
}

BYTE CDReadTOC(void *arg1,void *arg2)
{
	extern struct Library *CDPlayerBase;
	ULONG regs[16];
	regs[8] = (ULONG) arg1;
	regs[13] = (ULONG) arg2;
	__CallLibrary(CDPlayerBase,-90,regs);
	return (BYTE) regs[0];
}

BYTE CDInfo(void *arg1,void *arg2)
{
	extern struct Library *CDPlayerBase;
	ULONG regs[16];
	regs[8] = (ULONG) arg1;
	regs[13] = (ULONG) arg2;
	__CallLibrary(CDPlayerBase,-96,regs);
	return (BYTE) regs[0];
}

