// Stub functions for protofile "cybergraphics_protos.h"
// Generated by genPPCStub 1.1 for StormC
// © 1996/97 HAAGE & PARTNER GmbH

// DO NOT EDIT

#ifndef PPC
#define PPC
#endif // PPC

#include <libraries/powerpc.h>

#include <ppcamiga.h>

void *AllocCModeListTagList(void *arg1)
{
	extern struct Library *CyberGfxBase;
	ULONG regs[16];
	regs[9] = (ULONG) arg1;
	__CallLibrary(CyberGfxBase,-72,regs);
	return (void *) regs[0];
}

void *AllocCModeListTags(void *arg1)
{
	extern struct Library *CyberGfxBase;
	ULONG regs[16];
	regs[9] = (ULONG) &arg1;
	__CallLibrary(CyberGfxBase,-72,regs);
	return (void *) regs[0];
}

ULONG BestCModeIDTagList(void *arg1)
{
	extern struct Library *CyberGfxBase;
	ULONG regs[16];
	regs[8] = (ULONG) arg1;
	__CallLibrary(CyberGfxBase,-60,regs);
	return (ULONG) regs[0];
}

ULONG BestCModeIDTags(void *arg1)
{
	extern struct Library *CyberGfxBase;
	ULONG regs[16];
	regs[8] = (ULONG) &arg1;
	__CallLibrary(CyberGfxBase,-60,regs);
	return (ULONG) regs[0];
}

ULONG CModeRequestTagList(void *arg1,void *arg2)
{
	extern struct Library *CyberGfxBase;
	ULONG regs[16];
	regs[8] = (ULONG) arg1;
	regs[9] = (ULONG) arg2;
	__CallLibrary(CyberGfxBase,-66,regs);
	return (ULONG) regs[0];
}

ULONG CModeRequestTags(void *arg1,void *arg2)
{
	extern struct Library *CyberGfxBase;
	ULONG regs[16];
	regs[8] = (ULONG) arg1;
	regs[9] = (ULONG) &arg2;
	__CallLibrary(CyberGfxBase,-66,regs);
	return (ULONG) regs[0];
}

VOID CVideoCtrlTagList(void *arg1,void *arg2)
{
	extern struct Library *CyberGfxBase;
	ULONG regs[16];
	regs[8] = (ULONG) arg1;
	regs[9] = (ULONG) arg2;
	__CallLibrary(CyberGfxBase,-162,regs);
}

VOID CVideoCtrlTags(void *arg1,void *arg2)
{
	extern struct Library *CyberGfxBase;
	ULONG regs[16];
	regs[8] = (ULONG) arg1;
	regs[9] = (ULONG) &arg2;
	__CallLibrary(CyberGfxBase,-162,regs);
}

VOID DoCDrawMethodTagList(void *arg1,void *arg2,void *arg3)
{
	extern struct Library *CyberGfxBase;
	ULONG regs[16];
	regs[8] = (ULONG) arg1;
	regs[9] = (ULONG) arg2;
	regs[10] = (ULONG) arg3;
	__CallLibrary(CyberGfxBase,-156,regs);
}

VOID DoCDrawMethodTags(void *arg1,void *arg2,void *arg3)
{
	extern struct Library *CyberGfxBase;
	ULONG regs[16];
	regs[8] = (ULONG) arg1;
	regs[9] = (ULONG) arg2;
	regs[10] = (ULONG) &arg3;
	__CallLibrary(CyberGfxBase,-156,regs);
}

ULONG ExtractColor(void *arg1,void *arg2,ULONG arg3,ULONG arg4,ULONG arg5,ULONG arg6,ULONG arg7)
{
	extern struct Library *CyberGfxBase;
	ULONG regs[16];
	regs[8] = (ULONG) arg1;
	regs[9] = (ULONG) arg2;
	regs[0] = (ULONG) arg3;
	regs[1] = (ULONG) arg4;
	regs[2] = (ULONG) arg5;
	regs[3] = (ULONG) arg6;
	regs[4] = (ULONG) arg7;
	__CallLibrary(CyberGfxBase,-186,regs);
	return (ULONG) regs[0];
}

ULONG FillPixelArray(void *arg1,UWORD arg2,UWORD arg3,UWORD arg4,UWORD arg5,ULONG arg6)
{
	extern struct Library *CyberGfxBase;
	ULONG regs[16];
	regs[9] = (ULONG) arg1;
	regs[0] = (ULONG) arg2;
	regs[1] = (ULONG) arg3;
	regs[2] = (ULONG) arg4;
	regs[3] = (ULONG) arg5;
	regs[4] = (ULONG) arg6;
	__CallLibrary(CyberGfxBase,-150,regs);
	return (ULONG) regs[0];
}

VOID FreeCModeList(void *arg1)
{
	extern struct Library *CyberGfxBase;
	ULONG regs[16];
	regs[8] = (ULONG) arg1;
	__CallLibrary(CyberGfxBase,-78,regs);
}

ULONG GetCyberIDAttr(ULONG arg1,ULONG arg2)
{
	extern struct Library *CyberGfxBase;
	ULONG regs[16];
	regs[0] = (ULONG) arg1;
	regs[1] = (ULONG) arg2;
	__CallLibrary(CyberGfxBase,-102,regs);
	return (ULONG) regs[0];
}

ULONG GetCyberMapAttr(void *arg1,ULONG arg2)
{
	extern struct Library *CyberGfxBase;
	ULONG regs[16];
	regs[8] = (ULONG) arg1;
	regs[0] = (ULONG) arg2;
	__CallLibrary(CyberGfxBase,-96,regs);
	return (ULONG) regs[0];
}

ULONG InvertPixelArray(void *arg1,UWORD arg2,UWORD arg3,UWORD arg4,UWORD arg5)
{
	extern struct Library *CyberGfxBase;
	ULONG regs[16];
	regs[9] = (ULONG) arg1;
	regs[0] = (ULONG) arg2;
	regs[1] = (ULONG) arg3;
	regs[2] = (ULONG) arg4;
	regs[3] = (ULONG) arg5;
	__CallLibrary(CyberGfxBase,-144,regs);
	return (ULONG) regs[0];
}

WORD IsCyberModeID(ULONG arg1)
{
	extern struct Library *CyberGfxBase;
	ULONG regs[16];
	regs[0] = (ULONG) arg1;
	__CallLibrary(CyberGfxBase,-54,regs);
	return (WORD) regs[0];
}

void *LockBitMapTagList(void *arg1,void *arg2)
{
	extern struct Library *CyberGfxBase;
	ULONG regs[16];
	regs[8] = (ULONG) arg1;
	regs[9] = (ULONG) arg2;
	__CallLibrary(CyberGfxBase,-168,regs);
	return (void *) regs[0];
}

void *LockBitMapTags(void *arg1,void *arg2)
{
	extern struct Library *CyberGfxBase;
	ULONG regs[16];
	regs[8] = (ULONG) arg1;
	regs[9] = (ULONG) &arg2;
	__CallLibrary(CyberGfxBase,-168,regs);
	return (void *) regs[0];
}

ULONG MovePixelArray(UWORD arg1,UWORD arg2,void *arg3,UWORD arg4,UWORD arg5,UWORD arg6,UWORD arg7)
{
	extern struct Library *CyberGfxBase;
	ULONG regs[16];
	regs[0] = (ULONG) arg1;
	regs[1] = (ULONG) arg2;
	regs[9] = (ULONG) arg3;
	regs[2] = (ULONG) arg4;
	regs[3] = (ULONG) arg5;
	regs[4] = (ULONG) arg6;
	regs[5] = (ULONG) arg7;
	__CallLibrary(CyberGfxBase,-132,regs);
	return (ULONG) regs[0];
}

ULONG ReadPixelArray(void *arg1,UWORD arg2,UWORD arg3,UWORD arg4,void *arg5,UWORD arg6,UWORD arg7,UWORD arg8,UWORD arg9,UBYTE arg10)
{
	extern struct Library *CyberGfxBase;
	ULONG regs[16];
	regs[8] = (ULONG) arg1;
	regs[0] = (ULONG) arg2;
	regs[1] = (ULONG) arg3;
	regs[2] = (ULONG) arg4;
	regs[9] = (ULONG) arg5;
	regs[3] = (ULONG) arg6;
	regs[4] = (ULONG) arg7;
	regs[5] = (ULONG) arg8;
	regs[6] = (ULONG) arg9;
	regs[7] = (ULONG) arg10;
	__CallLibrary(CyberGfxBase,-120,regs);
	return (ULONG) regs[0];
}

ULONG ReadRGBPixel(void *arg1,UWORD arg2,UWORD arg3)
{
	extern struct Library *CyberGfxBase;
	ULONG regs[16];
	regs[9] = (ULONG) arg1;
	regs[0] = (ULONG) arg2;
	regs[1] = (ULONG) arg3;
	__CallLibrary(CyberGfxBase,-108,regs);
	return (ULONG) regs[0];
}

LONG ScalePixelArray(void *arg1,UWORD arg2,UWORD arg3,UWORD arg4,void *arg5,UWORD arg6,UWORD arg7,UWORD arg8,UWORD arg9,UBYTE arg10)
{
	extern struct Library *CyberGfxBase;
	ULONG regs[16];
	regs[8] = (ULONG) arg1;
	regs[0] = (ULONG) arg2;
	regs[1] = (ULONG) arg3;
	regs[2] = (ULONG) arg4;
	regs[9] = (ULONG) arg5;
	regs[3] = (ULONG) arg6;
	regs[4] = (ULONG) arg7;
	regs[5] = (ULONG) arg8;
	regs[6] = (ULONG) arg9;
	regs[7] = (ULONG) arg10;
	__CallLibrary(CyberGfxBase,-90,regs);
	return (LONG) regs[0];
}

VOID UnLockBitMap(void *arg1)
{
	extern struct Library *CyberGfxBase;
	ULONG regs[16];
	regs[8] = (ULONG) arg1;
	__CallLibrary(CyberGfxBase,-174,regs);
}

ULONG WritePixelArray(void *arg1,UWORD arg2,UWORD arg3,UWORD arg4,void *arg5,UWORD arg6,UWORD arg7,UWORD arg8,UWORD arg9,UBYTE arg10)
{
	extern struct Library *CyberGfxBase;
	ULONG regs[16];
	regs[8] = (ULONG) arg1;
	regs[0] = (ULONG) arg2;
	regs[1] = (ULONG) arg3;
	regs[2] = (ULONG) arg4;
	regs[9] = (ULONG) arg5;
	regs[3] = (ULONG) arg6;
	regs[4] = (ULONG) arg7;
	regs[5] = (ULONG) arg8;
	regs[6] = (ULONG) arg9;
	regs[7] = (ULONG) arg10;
	__CallLibrary(CyberGfxBase,-126,regs);
	return (ULONG) regs[0];
}

ULONG WriteLUTPixelArray(void *arg1,UWORD arg2,UWORD arg3,UWORD arg4,void *arg5,void *arg6,UWORD arg7,UWORD arg8,UWORD arg9,UWORD arg10,UBYTE arg11)
{
	extern struct Library *CyberGfxBase;
	ULONG regs[16];
	regs[8] = (ULONG) arg1;
	regs[0] = (ULONG) arg2;
	regs[1] = (ULONG) arg3;
	regs[2] = (ULONG) arg4;
	regs[9] = (ULONG) arg5;
	regs[10] = (ULONG) arg6;
	regs[3] = (ULONG) arg7;
	regs[4] = (ULONG) arg8;
	regs[5] = (ULONG) arg9;
	regs[6] = (ULONG) arg10;
	regs[7] = (ULONG) arg11;
	__CallLibrary(CyberGfxBase,-198,regs);
	return (ULONG) regs[0];
}

LONG WriteRGBPixel(void *arg1,UWORD arg2,UWORD arg3,ULONG arg4)
{
	extern struct Library *CyberGfxBase;
	ULONG regs[16];
	regs[9] = (ULONG) arg1;
	regs[0] = (ULONG) arg2;
	regs[1] = (ULONG) arg3;
	regs[2] = (ULONG) arg4;
	__CallLibrary(CyberGfxBase,-114,regs);
	return (LONG) regs[0];
}

VOID UnLockBitMapTagList(void *arg1,void *arg2)
{
	extern struct Library *CyberGfxBase;
	ULONG regs[16];
	regs[8] = (ULONG) arg1;
	regs[9] = (ULONG) arg2;
	__CallLibrary(CyberGfxBase,-180,regs);
}

VOID UnLockBitMapTags(void *arg1,void *arg2)
{
	extern struct Library *CyberGfxBase;
	ULONG regs[16];
	regs[8] = (ULONG) arg1;
	regs[9] = (ULONG) &arg2;
	__CallLibrary(CyberGfxBase,-180,regs);
}

