// Stub functions for protofile "lowlevel_protos.h"
// Generated by genPPCStub 1.1 for StormC
// © 1996/97 HAAGE & PARTNER GmbH

// DO NOT EDIT

#ifndef PPC
#define PPC
#endif // PPC

#include <libraries/powerpc.h>

#include <ppcamiga.h>

ULONG ReadJoyPort(ULONG arg1)
{
	extern struct Library *LowLevelBase;
	ULONG regs[16];
	regs[0] = (ULONG) arg1;
	__CallLibrary(LowLevelBase,-30,regs);
	return (ULONG) regs[0];
}

UBYTE GetLanguageSelection()
{
	extern struct Library *LowLevelBase;
	ULONG regs[16];
	__CallLibrary(LowLevelBase,-36,regs);
	return (UBYTE) regs[0];
}

ULONG GetKey()
{
	extern struct Library *LowLevelBase;
	ULONG regs[16];
	__CallLibrary(LowLevelBase,-48,regs);
	return (ULONG) regs[0];
}

VOID QueryKeys(void *arg1,ULONG arg2)
{
	extern struct Library *LowLevelBase;
	ULONG regs[16];
	regs[8] = (ULONG) arg1;
	regs[1] = (ULONG) arg2;
	__CallLibrary(LowLevelBase,-54,regs);
}

void *AddKBInt(void *arg1,void *arg2)
{
	extern struct Library *LowLevelBase;
	ULONG regs[16];
	regs[8] = (ULONG) arg1;
	regs[9] = (ULONG) arg2;
	__CallLibrary(LowLevelBase,-60,regs);
	return (void *) regs[0];
}

VOID RemKBInt(void *arg1)
{
	extern struct Library *LowLevelBase;
	ULONG regs[16];
	regs[9] = (ULONG) arg1;
	__CallLibrary(LowLevelBase,-66,regs);
}

ULONG SystemControlA(void *arg1)
{
	extern struct Library *LowLevelBase;
	ULONG regs[16];
	regs[9] = (ULONG) arg1;
	__CallLibrary(LowLevelBase,-72,regs);
	return (ULONG) regs[0];
}

ULONG SystemControl(void *arg1)
{
	extern struct Library *LowLevelBase;
	ULONG regs[16];
	regs[9] = (ULONG) &arg1;
	__CallLibrary(LowLevelBase,-72,regs);
	return (ULONG) regs[0];
}

void *AddTimerInt(void *arg1,void *arg2)
{
	extern struct Library *LowLevelBase;
	ULONG regs[16];
	regs[8] = (ULONG) arg1;
	regs[9] = (ULONG) arg2;
	__CallLibrary(LowLevelBase,-78,regs);
	return (void *) regs[0];
}

VOID RemTimerInt(void *arg1)
{
	extern struct Library *LowLevelBase;
	ULONG regs[16];
	regs[9] = (ULONG) arg1;
	__CallLibrary(LowLevelBase,-84,regs);
}

VOID StopTimerInt(void *arg1)
{
	extern struct Library *LowLevelBase;
	ULONG regs[16];
	regs[9] = (ULONG) arg1;
	__CallLibrary(LowLevelBase,-90,regs);
}

VOID StartTimerInt(void *arg1,ULONG arg2,LONG arg3)
{
	extern struct Library *LowLevelBase;
	ULONG regs[16];
	regs[9] = (ULONG) arg1;
	regs[0] = (ULONG) arg2;
	regs[1] = (ULONG) arg3;
	__CallLibrary(LowLevelBase,-96,regs);
}

ULONG ElapsedTime(void *arg1)
{
	extern struct Library *LowLevelBase;
	ULONG regs[16];
	regs[8] = (ULONG) arg1;
	__CallLibrary(LowLevelBase,-102,regs);
	return (ULONG) regs[0];
}

void *AddVBlankInt(void *arg1,void *arg2)
{
	extern struct Library *LowLevelBase;
	ULONG regs[16];
	regs[8] = (ULONG) arg1;
	regs[9] = (ULONG) arg2;
	__CallLibrary(LowLevelBase,-108,regs);
	return (void *) regs[0];
}

VOID RemVBlankInt(void *arg1)
{
	extern struct Library *LowLevelBase;
	ULONG regs[16];
	regs[9] = (ULONG) arg1;
	__CallLibrary(LowLevelBase,-114,regs);
}

BOOL SetJoyPortAttrsA(ULONG arg1,void *arg2)
{
	extern struct Library *LowLevelBase;
	ULONG regs[16];
	regs[0] = (ULONG) arg1;
	regs[9] = (ULONG) arg2;
	__CallLibrary(LowLevelBase,-132,regs);
	return (BOOL) regs[0];
}

BOOL SetJoyPortAttrs(ULONG arg1,void *arg2)
{
	extern struct Library *LowLevelBase;
	ULONG regs[16];
	regs[0] = (ULONG) arg1;
	regs[9] = (ULONG) &arg2;
	__CallLibrary(LowLevelBase,-132,regs);
	return (BOOL) regs[0];
}

