// Stub functions for protofile "graphics_protos.h"
// Generated by genPPCStub 1.1 for StormC
// © 1996/97 HAAGE & PARTNER GmbH

// DO NOT EDIT

#ifndef PPC
#define PPC
#endif // PPC

#include <libraries/powerpc.h>

#include <ppcamiga.h>

VOID WriteChunkyPixels(void *arg1,ULONG arg2,ULONG arg3,ULONG arg4,ULONG arg5,void *arg6,LONG arg7)
{
	extern struct Library *GfxBase;
	ULONG regs[16];
	regs[8] = (ULONG) arg1;
	regs[0] = (ULONG) arg2;
	regs[1] = (ULONG) arg3;
	regs[2] = (ULONG) arg4;
	regs[3] = (ULONG) arg5;
	regs[10] = (ULONG) arg6;
	regs[4] = (ULONG) arg7;
	__CallLibrary(GfxBase,-1056,regs);
}
